#!/bin/sh
KEYDIR=/etc/dropbear

case "$1" in
	start)
		# Check for the Dropbear RSA key
		if [[ ! -f $KEYDIR/dropbear_rsa_host_key || ! -f $KEYDIR/dropbear_rsa_host_key.pub ]] ; then
			rm -f $KEYDIR/dropbear_rsa_host_key*
			echo "Generating RSA key ..."
			dropbearkey -t rsa -f $KEYDIR/dropbear_rsa_host_key	| grep "^ssh-rsa " > $KEYDIR/dropbear_rsa_host_key.pub
		fi
		;;
	stop)
		;;
	*)
		echo "Usage: $0 start" >&2
		exit 1
		;;
esac
